// Automatically generated by scripts/deploy.js
module.exports = {
  CURRENT: { address: "0x40aEd3065673975ad7a52C71ACa1FCBBb41bE681", chainId: 11155111, firstChallengeId: 2001, hasFee: true, hasLock: true },
  // Older contracts that still hold challenges (IDs below CURRENT.firstChallengeId)
  LEGACY_DEPLOYMENTS: [
  {
    "address": "0x92260222110C5EB79a5Cd2989c0D03CcC92658FC",
    "firstChallengeId": 1001,
    "hasFee": true,
    "hasLock": false
  }
],
};
