const { ethers, network } = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  console.log(`\n========================================`);
  console.log(`🚀 Deploying CommitX Protocol to: ${network.name}`);
  console.log(`========================================\n`);

  const [deployer] = await ethers.getSigners();
  console.log(`Deployer address: ${deployer.address}`);

  const balance = await ethers.provider.getBalance(deployer.address);
  console.log(`Deployer balance: ${ethers.formatEther(balance)} ETH`);

  // Default attestor & treasury configuration
  // In development, deployer or configured env accounts
  const attestorAddress = process.env.PROTOCOL_ATTESTOR_ADDRESS || deployer.address;
  const treasuryAddress = process.env.TREASURY_ADDRESS || deployer.address;

  console.log(`Configuring Attestor: ${attestorAddress}`);
  console.log(`Configuring Treasury: ${treasuryAddress}`);

  // New deployments start IDs after the previous contract's IDs so they never collide.
  // A previous contract with no challenges is simply retired (its ID range is reused).
  const configDirEarly = path.join(__dirname, "../src/config");
  const bookPath = path.join(configDirEarly, "deployments.js");
  const prevBook = fs.existsSync(bookPath) ? require(bookPath) : null;
  let prevChallengeCount = 0;
  let prevNextId = null;
  if (prevBook?.CURRENT && Number(prevBook.CURRENT.chainId) === Number(network.config.chainId || 31337)) {
    try {
      const prevContract = new ethers.Contract(
        prevBook.CURRENT.address,
        ["function nextChallengeId() view returns (uint256)", "function firstChallengeId() view returns (uint256)"],
        ethers.provider
      );
      const [next, first] = await Promise.all([prevContract.nextChallengeId(), prevContract.firstChallengeId()]);
      prevNextId = Number(next);
      prevChallengeCount = Number(next - first);
    } catch {
      prevChallengeCount = 1; // can't tell → keep routing to it, to be safe
    }
  }
  const autoFirst =
    prevChallengeCount > 0 && prevNextId ? Math.ceil(prevNextId / 1000) * 1000 + 1 : prevBook?.CURRENT?.firstChallengeId || (network.name === "sepolia" ? 1001 : 1);
  const firstChallengeId = Number(process.env.FIRST_CHALLENGE_ID || autoFirst);
  console.log(`Previous contract:    ${prevBook?.CURRENT?.address || "none"} (${prevChallengeCount} challenges)`);
  console.log(`First challenge ID:   ${firstChallengeId}`);

  const CommitXProtocol = await ethers.getContractFactory("CommitXProtocol");
  const protocol = await CommitXProtocol.deploy(attestorAddress, treasuryAddress, firstChallengeId);
  await protocol.waitForDeployment();

  const contractAddress = await protocol.getAddress();
  console.log(`\n✅ CommitXProtocol deployed successfully at: ${contractAddress}`);

  // The in-memory "hardhat" network disappears after this script — never point the app at it
  if (network.name === "hardhat") {
    console.log("(In-memory hardhat network: config files left unchanged.)");
    return;
  }

  // Extract ABI from Hardhat artifacts
  const artifactPath = path.join(
    __dirname,
    "../artifacts/contracts/CommitXProtocol.sol/CommitXProtocol.json"
  );
  const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf8"));

  // Ensure config directory exists
  const configDir = path.join(__dirname, "../src/config");
  if (!fs.existsSync(configDir)) {
    fs.mkdirSync(configDir, { recursive: true });
  }

  // Export contract configuration for frontend and backend
  const contractConfigFile = path.join(configDir, "contracts.js");
  const configContent = `// Automatically generated by scripts/deploy.js
module.exports = {
  COMMITX_CONTRACT_ADDRESS: "${contractAddress}",
  COMMITX_CHAIN_ID: ${network.config.chainId || 31337},
  COMMITX_NETWORK_NAME: "${network.name}",
  COMMITX_FIRST_CHALLENGE_ID: ${firstChallengeId},
  COMMITX_ABI: ${JSON.stringify(artifact.abi, null, 2)},
};
`;

  fs.writeFileSync(contractConfigFile, configContent);

  // Lightweight address book (no ABI) for code that only needs addresses
  const book = path.join(configDir, "deployments.js");
  const prev = fs.existsSync(book) ? require(book) : null;
  const legacy = [...(prev?.LEGACY_DEPLOYMENTS || [])];
  // The contract being replaced keeps its challenges — route its ID range to it
  if (
    prevChallengeCount > 0 &&
    prev?.CURRENT &&
    prev.CURRENT.address.toLowerCase() !== contractAddress.toLowerCase() &&
    !legacy.some((d) => d.address.toLowerCase() === prev.CURRENT.address.toLowerCase())
  ) {
    legacy.unshift({
      address: prev.CURRENT.address,
      firstChallengeId: prev.CURRENT.firstChallengeId,
      hasFee: Boolean(prev.CURRENT.hasFee),
      hasLock: Boolean(prev.CURRENT.hasLock),
    });
  }
  fs.writeFileSync(
    book,
    `// Automatically generated by scripts/deploy.js
module.exports = {
  CURRENT: { address: "${contractAddress}", chainId: ${network.config.chainId || 31337}, firstChallengeId: ${firstChallengeId}, hasFee: true, hasLock: true },
  // Older contracts that still hold challenges (IDs below CURRENT.firstChallengeId)
  LEGACY_DEPLOYMENTS: ${JSON.stringify(legacy, null, 2)},
};
`
  );
  console.log(`📄 Contract config & ABI saved to: src/config/contracts.js`);
  console.log(`\n========================================\n`);
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
